first/config/routes.rb
RubyExercise::Application.routes.draw do
  get "sign_up" => "users#new", :as  => "sign_up"
  root :to => 'users#new'
  resources :users

	resources :articles,:users, :products, :categories, :countries

  

end

first/app/models/article.rb
class Article < ActiveRecord::Base
#	params :title,:description,:rating,:user_id

	belongs_to 	:user,
							:class_name => "User",
							:foreign_key => "user_id"
	has_many :comments, :dependent => :destroy
	scope :rating, lambda {|rating| where("rating >= ?", rating)}
	scope :more_100_chars, -> {where("length(description)>100")}

validates :title,
		      :presence =>true, 
		      :uniqueness=>true,
		      :allow_nil=>false,
          :allow_blank=>false
end

first/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def create
    @article=Article.new(article_params)
	  if @article.save
			redirect_to articles_path,:notice=>"Article added"
		else
			render 'new'
		end  
  end

  	def new
    	@article=Article.new
  	end
  
  	def show
		@article=Article.find(params[:id])
	end
  
	def edit
		@article=Article.find(params[:id])
	end

  	def update
		@article=Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to articles_path,:notice=>"Article updated"
		else
			render 'edit'
		end
	end
  
  def index
    @article=Article.all
  end
  
  	def destroy
		@article=Article.find(params[:id])
	  Article.delete(params[:id])
		redirect_to articles_path, :notice => "Article deleted"
	end

  private

  def article_params
    params.require(:article).permit(:title, :description, :rating)
  end
end

first/app/helpers/articles_helper.rb
module ArticlesHelper
end

first/app/views/articles/edit.html.erb
<h1>Edit Artikel</h1>
<%= form_for :article,url:article_path(@article.id),method:"put" do |form| %>
<% if @article.errors.any? %>
			<h4 style="color:red">
        <%= pluralize(@article.errors.count, "error") %> prohibited this post from being saved:</h4>
      <h3 style="color:red">
        <% @article.errors.full_messages.each do |msg| %><br>
					<%= msg %>
				<% end %>
      </h3>
<% end %>

  <p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description,size:"70x15" %>
	</p>
	<p>
		<%= form.label :rating %><br>
		<%= form.select(:rating,options_for_select([[0],[1],[2],[3],[4],[5]],@article.rating)) %>
	</p>
	<p>
		<%= form.submit %> &nbsp; 
		<%= link_to "Back",articles_path,class:"button" %>
	</p>
<% end %>

first/app/views/articles/index.html.erb
<h1>This is Index Of Article</h1>

<table>
<tr>
  <th>No</th>
  <th>Title</th>
  <th colspan="3">Action</th>
</tr>
<% no=0 %>
<% @article.each do |artikel| %>
  <% no=no+1 %>
<tr>
  <td><%= no %></td>
  <td width="200px"><%= artikel.title %></td>
  <td><%= link_to "View",article_path(artikel.id) %></td>
  <td><%= link_to "Edit",edit_article_path(artikel.id) %></td>
  <td><%= link_to("Delete",article_path(artikel.id),method: :delete,confirm:"Are you sure you want to Delete?") %></td>
</tr>
<% end %>
</table>
<br>
<%= link_to "Tambah Artikel!",new_article_path,class:"button" %><br>
<br><br>

first/app/views/articles/new.html.erb
<!--<h1>New Article</h1>

<%= form_for @article do |f| %>
  Title name: <%= f.text_field :title %><br>
  <%=f.submit :Okay%>
<% end %>-->

<h1>Articles</h1>
	<%= form_for :article, url: articles_path do |form| %>
		<% if @article.errors.any? %>
				<h4 style="color:red">
	        <%= pluralize(@article.errors.count, "error") %> prohibited this post from being saved:</h4>
	      <h3 style="color:red">
	        <% @article.errors.full_messages.each do |msg| %><br>
						<%= msg %>
					<% end %>
	      </h3>
		<% end %>
	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description,size:"70x15" %>
	</p>
	<p>
		<%= form.label :rating %><br>
		<%= form.select(:rating,options_for_select([[0],[1],[2],[3],[4],[5]])) %>
	</p>
	<p>
		<%= form.submit %> &nbsp; 
		<%= link_to "Back",articles_path,class:"button" %>
	</p>
<% end %>

first/app/views/articles/show.html.erb
<h1>Articles</h1>
<article>
	<p>
		<strong>Title</strong><br>
		<%= @article.title %>
	</p>
	<p>
		<strong>Description</strong><br>
		<%= simple_format(@article.description) %>
	</p>
	<p>
		<strong>Rating</strong><br>
		<%= @article.rating %>
	</p>
	<p>
<%= link_to "Back",articles_path,class:"button" %>
</article>