first/config/routes.rb
RubyExercise::Application.routes.draw do
  get "sign_up" => "users#new", :as  => "sign_up"
  root :to => 'users#new'
  resources :users

	resources :articles,:users, :products, :categories, :countries

  

end

first/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, :through => :user
	has_many :users
	belongs_to :product,
	     :class_name => "Product",
	     :foreign_key => "product_id"
	scope :category, lambda {|name| where("name = ?", name)}

  has_many :shoes_products,
        :class_name => "Product",
        :conditions => "name like '%Shoes%'"

validates :name,
		      :presence =>true, 
		      :uniqueness=>true,
		      :allow_nil=>false,
          :allow_blank=>false
end

first/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def create
     @category=Category.new(category_params)
	  if @category.save
			redirect_to categories_path,:notice=>"Article added"
		else
			render 'new'
		end  
  end

  def edit
    @category=Category.find(params[:id])
  end

    def update
    @category=Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to categories_path,:notice=>"Category updated"
    else
      render 'edit'
    end
  end

  def destroy
    @category=Category.find(params[:id])
    Category.delete(params[:id])
    redirect_to categories_path, :notice => "Category deleted"
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

first/app/helpers/categories_helper.rb
module CategoriesHelper
end

first/app/views/categories/edit.html.erb
<h1>New Category</h1>

 <%= form_for :category,url:category_path(@category.id),method:"put" do |form| %>
	<% if @category.errors.any? %>
		<h4 style="color:red">
	        <%= pluralize(@category.errors.count, "error") %> prohibited this post from being saved:</h4>
	    <h3 style="color:red">
	        <% @category.errors.full_messages.each do |msg| %><br>
						<%= msg %>
					<% end %>
	      </h3>
		<% end %>
 <p>
		<%= form.label :name %><br>
		<%= form.text_field :name %>
	</p>

	<p>
		<%= form.submit("Edit Kategori") %>
		<%= link_to "Back",categories_path,class:"button" %>
	</p>
<% end %>

first/app/views/categories/index.html.erb
<h1>This is Index for Category</h1>
<% no=0 %>
<% @category.each do |kategori| %>
  <% no=no+1 %>
  <%= no %>.
  <%= kategori.name %>
  <%= link_to "View",category_path(kategori.id) %>
  <%= link_to "Edit",edit_category_path(kategori.id) %>
  <%= link_to("Delete",category_path(kategori.id),method: :delete,confirm:"Are you sure you want to Delete?") %><br>
<% end %>
<br><br>
<%= link_to "Tambah Kategori!",new_category_path,class:"button" %><br>

first/app/views/categories/new.html.erb
<h1>New Category</h1>

 <%= form_for @category do |form| %>
	<% if @category.errors.any? %>
		<h4 style="color:red">
	        <%= pluralize(@category.errors.count, "error") %> prohibited this post from being saved:</h4>
	    <h3 style="color:red">
	        <% @category.errors.full_messages.each do |msg| %><br>
						<%= msg %>
					<% end %>
	      </h3>
		<% end %>
 <p>
		<%= form.label :name %><br>
		<%= form.text_field :name %>
	</p>

	<p>
		<%= form.submit("Tambah Kategori") %>
		<%= link_to "Back",categories_path,class:"button" %>
	</p>
<% end %>