Ruby/config/routes.rb
RubyExercise::Application.routes.draw do
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out"
          resources :articles,:categories,:comments,:countries,:products,:users,:sessions
  
  namespace :admin do
  resources :articles,:categories,:comments,:countries,:products,:users
  end
  root :to => 'sessions#new'

  

end

Ruby/app/models/article.rb
class Article < ActiveRecord::Base
#	params :title,:description,:rating,:user_id

	belongs_to 	:user,
							:class_name => "User",
							:foreign_key => "user_id"
	has_many :comments, :dependent => :destroy
	scope :rating, lambda {|rating| where("rating >= ?", rating)}
	scope :more_100_chars, -> {where("length(description)>100")}

validates :title,
		      :presence =>true, 
		      :uniqueness=>true,
		      :allow_nil=>false,
          :allow_blank=>false
end

Ruby/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, :through => :user
	has_many :users
	belongs_to :product,
	     :class_name => "Product",
	     :foreign_key => "product_id"
	scope :category, lambda {|name| where("name = ?", name)}

  has_many :shoes_products,
        :class_name => "Product",
        :conditions => "name like '%Shoes%'"

validates :name,
		      :presence =>true, 
		      :uniqueness=>true,
		      :allow_nil=>false,
          :allow_blank=>false
end

Ruby/app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
end

Ruby/app/models/column.rb
class Column < ActiveRecord::Base
end

Ruby/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :article
end

Ruby/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :users
  has_many :indonesian_users,
           :class_name => "User",
           :conditions => "country_id = '6'"

	validates_inclusion_of :code, :in => %w(id ua frc)
end

Ruby/app/models/manipulate.rb
class Manipulate < ActiveRecord::Base
end

Ruby/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :category, :through => :user
  has_many :user
  scope :price, lambda {|price| where("price <= ?", price)}
  scope :stock, lambda {|stock| where("stock = ?", stock)}

validates :price,
		  :presence =>true, 
		  :allow_nil=>false,
          :numericality=>true
end

Ruby/app/models/relation.rb
class Relation < ActiveRecord::Base
has_many :users, :dependent => :destroy
end

class Product < ActiveRecord::Base
  belongs_to :products
end

Ruby/app/models/user.rb
class User < ActiveRecord::Base
#   attr_accessible :email, :password, :password_confirmation, :age, :address
# 	Penting untuk ditanya coba tanya

	has_one :country
	has_many :articles, :dependent => :destroy
	has_many :products, :dependent => :destroy
	has_many :comments, :dependent => :destroy
	belongs_to :category
	belongs_to :product
  has_many :articles_my_country,
           :class_name => "Article",
           :conditions => "description like '%my_country%'"

	scope :age, -> {where("age >= 18")}
	scope :from, lambda {|country| where(country_id: country) }
	scope :indonesian, -> {where(country_id: Country.find_by_name("Indonesia").id)}

  def valid_name
    self.errors[:first_name] << "Can't filled by Martin"
  end

	def show_address
	   "Alamat: #{self.address} Negara: #{country.name}"
	end
	
	def self.show_age
	   "#{self.first_name} #{self.last_name}"
	end

	def encrypt_password
		if password.present?
			self.password_salt=BCrypt::Engine.generate_salt
			self.password_hash=BCrypt::Engine.hash_secret(password,password_salt)
		end
	end
	
	def self.authenticate(email,password)
		user=find_by_email(email)
		if user&&user.password_hash==BCrypt::Engine.hash_secret(password,user.password_salt)
			user
		else
			nil
		end
	end

#  validate :valid_name
	attr_accessor :password
	before_save :encrypt_password

	validates :password,
		:presence => {:on => :create},
		:confirmation => true

  	validates :first_name,
		:presence =>true, 
		:length=>{:minimum=>1,:maximum=>20},
#		:format=>{:with=> /[a-zA-Z\s]+$/},
		:uniqueness=>true,
		:allow_nil=>false		

#	validates :last_name,
#		:presence =>true, 
#		:length=>{:minimum=>1,:maximum=>20},
#		:format=>{:with=> /[a-zA-Z\s]+$/},
#		:allow_nil=>false
		
	validates :email,
		:presence=>true, 
		:length=>{:minimum => 3, :maximum => 254},
		:uniqueness=>true,
#		:format=>{:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i},
		:allow_nil=>false
end

Ruby/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :require_login, :only => [:index,:new, :create, :edit, :update, :destroy]

  	def create
		@article=Article.new(article_params)
			if @article.save
				redirect_to articles_path,:notice=>"Article added"
			else
				render 'new'
			end  
  	end

  	def new
    	@article=Article.new
  	end
  
  	def show
		@article=Article.find(params[:id])
	end
  
	def edit
		@article=Article.find(params[:id])
	end

  	def update
		@article=Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to articles_path,:notice=>"Article updated"
		else
			render 'edit'
		end
	end
  
  	def index
    	@article=Article.all
  	end
  
  	def destroy
		@article=Article.find(params[:id])
		if @article.user_id==@current_user.id
			Comment.delete_all(["article_id=?" ,params[:id]])
			Article.delete(params[:id])
			redirect_to articles_path, :notice => "Article deleted"
		else
			redirect_to articles_path, :notice=>"Article doesn't belong to you"
		end
	end

  private

  	def article_params
    	params.require(:article).permit(:title, :description, :rating, :user_id)
  	end
end

Ruby/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :require_login, :only => [:index, :edit, :update, :delete]
 def index
    @user =User.all
  end
  
  def new
    @user =User.new
  end
 
  def create
    @user = User.new(user_params)
    if verify_recaptcha
      if @user.save
      #  UserMailer.registration_confirmation(@user).deliver
        redirect_to users_path,:notice=>"Sign Up"
      else
        render 'new'
      end  
    else
        flash[:error] = "There was an error with the recaptcha code below."
        render 'new'
    end      
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
		@user=User.find(params[:id])
	end

  def update
		@user=User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path,:notice=>"Article updated"
		else
			render 'edit'
		end
	end

  def destroy
    @user=User.find(params[:id])
	  User.delete(params[:id])
		redirect_to users_path, :notice => "Article deleted"
  end

  private 

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :date_of_birth, :age, :address, :country_id)
  end 
end

Ruby/app/helpers/application_helper.rb
module ApplicationHelper
	def welcome_text
		 str = "" # if the user has logged in, show the welcome text.
		 if current_user
			 str = "Welcome, #{current_user.email} | "
			 str += link_to "Logout", log_out_path
		 else
			 str = "#{link_to "Login", log_in_path} | "
			 str += link_to "Signup", sign_up_path
	 	end
	end 
end

Ruby/app/helpers/articles_helper.rb
module ArticlesHelper
end

Ruby/app/helpers/categories_helper.rb
module CategoriesHelper
end

Ruby/app/helpers/comments_helper.rb
module CommentsHelper
end

Ruby/app/helpers/countries_helper.rb
module CountriesHelper
end

Ruby/app/helpers/products_helper.rb
module ProductsHelper
end

Ruby/app/helpers/sessions_helper.rb
module SessionsHelper
end

Ruby/app/helpers/users_helper.rb
module UsersHelper
end

Ruby/app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Application | Hasan AL Farisi</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav id="menu">
			<ul>	
				<li><%= link_to "Articles",articles_path %></li>
				<li><%= link_to "Users",users_path %></li>
				<li><%= link_to "Products",products_path %></li>
				<li><%= link_to "Categories",categories_path %></li>
				<li><%= link_to "Countries",countries_path %></li>
				<li><%= link_to "Comments",comments_path %></li>
			</ul>
		</nav>
		<nav id="status">
			<%= raw(welcome_text) %>
		</nav>
		<article id="content">
			<%= yield %>
		</article>
	</body>
</html>

Ruby/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Application</title>
		<%= stylesheet_link_tag "admin", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
  </head>
  <body>
    <nav id="menu">
        <%= link_to "Articles",admin_articles_path %>&nbsp;|
        <%= link_to "Users",admin_users_path %>&nbsp;|
        <%= link_to "Products",admin_products_path %>&nbsp;|
        <%= link_to "Categories",admin_categories_path %>&nbsp;|
        <%= link_to "Countries",admin_countries_path %>&nbsp;|
        <%= link_to "Comments",admin_comments_path %>
    </nav>
    <nav id="status">
      <%= raw(welcome_text) %>
    </nav>
    <article id="content">
      <%= yield %>
    </article>
  </body>

Ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Exercise</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "JQuery", "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav id="menu">
        <%= link_to "Articles",articles_path %>&nbsp;|
        <%= link_to "Users",users_path %>&nbsp;|
        <%= link_to "Products",products_path %>&nbsp;|
        <%= link_to "Categories",categories_path %>&nbsp;|
        <%= link_to "Countries",countries_path %>&nbsp;|
        <%= link_to "Comments",comments_path %>
    </nav>
    <nav id="status">
      <%= raw(welcome_text) %>
    </nav>
    <article id="content">
      <%= yield %>
    </article>
  </body>
</html>