Ruby/config/routes.rb
RubyExercise::Application.routes.draw do
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in" 
  get "log_out" => "sessions#destroy", :as => "log_out"
          resources :articles,:categories,:comments,:countries,:products,:users,:sessions
  
  namespace :admin do
  resources :articles,:categories,:comments,:countries,:products,:users
  end
  root :to => 'sessions#new'

  

end

Ruby/app/models/article.rb
class Article < ActiveRecord::Base
#	params :title,:description,:rating,:user_id

	belongs_to 	:user,
							:class_name => "User",
							:foreign_key => "user_id"
	has_many :comments, :dependent => :destroy
	scope :rating, lambda {|rating| where("rating >= ?", rating)}
	scope :more_100_chars, -> {where("length(description)>100")}

validates :title,
		      :presence =>true, 
		      :uniqueness=>true,
		      :allow_nil=>false,
          :allow_blank=>false
end

Ruby/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
 	before_filter :require_admin_login
  
  	def create
	    @article=Article.new(article_params)
		if @article.save
			redirect_to admin_articles_path,:notice=>"Article added"
		else
			render 'new'
		end  
  	end

  	def new
    	@article=Article.new
  	end
  
  	def show
		@article=Article.find(params[:id])
	end
  
	def edit
		@article=Article.find(params[:id])
	end

  	def update
		@article=Article.find(params[:id])
		if 	@article.update_attributes(article_params)
			redirect_to admin_articles_path,:notice=>"Article updated"
		else
			render 'edit'
		end
	end
  
  	def index
    	@article=Article.all
  	end
  
  	def destroy
		@article=Article.find(params[:id])
		if @article.user_id==@current_user.id
			Comment.delete_all(["article_id=?" ,params[:id]])
			Article.delete(params[:id])
			redirect_to admin_articles_path, :notice => "Article deleted"
		else
			redirect_to admin_articles_path, :notice=>"Article doesn't belong to you"
		end
	end

  private

  def article_params
    	params.require(:article).permit(:title, :description, :rating, :user_id)
  end
end

Ruby/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :require_login, :only => [:index,:new, :create, :edit, :update, :destroy]

  	def create
		@article=Article.new(article_params)
			if @article.save
				redirect_to articles_path,:notice=>"Article added"
			else
				render 'new'
			end  
  	end

  	def new
    	@article=Article.new
  	end
  
  	def show
		@article=Article.find(params[:id])
	end
  
	def edit
		@article=Article.find(params[:id])
	end

  	def update
		@article=Article.find(params[:id])
		if @article.update_attributes(article_params)
			redirect_to articles_path,:notice=>"Article updated"
		else
			render 'edit'
		end
	end
  
  	def index
    	@article=Article.all
  	end
  
  	def destroy
		@article=Article.find(params[:id])
		if @article.user_id==@current_user.id
			Comment.delete_all(["article_id=?" ,params[:id]])
			Article.delete(params[:id])
			redirect_to articles_path, :notice => "Article deleted"
		else
			redirect_to articles_path, :notice=>"Article doesn't belong to you"
		end
	end

  private

  	def article_params
    	params.require(:article).permit(:title, :description, :rating, :user_id)
  	end
end

Ruby/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

Ruby/app/helpers/articles_helper.rb
module ArticlesHelper
end

Ruby/app/views/admin/articles/_comments.html.erb
<% comments.each do |comment| %>
	<span><%= comment.content %></span><br>
<% end %>

Ruby/app/views/admin/articles/edit.html.erb
<h1>Edit Artikel</h1>
<%= form_for :article,url:admin_article_path(@article.id),method:"put" do |form| %>
<% if @article.errors.any? %>
	<h4 style="color:red">
        <%= pluralize(@article.errors.count, "error") %> prohibited this post from being saved:
    </h4>
    <h3 style="color:red">
        <% @article.errors.full_messages.each do |msg| %><br>
			<%= msg %>
		<% end %>
    </h3>
<% end %>

  	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description,size:"70x15" %>
	</p>

	<p>
		<%= form.label :rating %><br>
		<%= form.select(:rating,options_for_select([[0],[1],[2],[3],[4],[5]],@article.rating)) %>
	</p>
	
	<p>
		<%= form.submit %> &nbsp; 
		<%= link_to "Back",admin_articles_path,class:"button" %>
	</p>
<% end %>

Ruby/app/views/admin/articles/index.html.erb
<h1>This is Index Of Article</h1>

<table>
	<tr>
	  	<th>No</th>
	  	<th>Title</th>
	  	<th colspan="3">Action</th>
	</tr>
	<% no=0 %>
	<% @article.each do |artikel| %>
  	<% no=no+1 %>
		<tr>
		  	<td><%= no %></td>
		  	<td width="200px"><%= artikel.title %></td>
		  	<td><%= link_to "View",admin_article_path(artikel.id) %></td>
		  	<td><%= link_to "Edit",edit_admin_article_path(artikel.id) %></td>
		  	<td><%= link_to("Delete",admin_article_path(artikel.id),method: :delete,confirm:"Are you sure you want to Delete?") %></td>
		</tr>
	<% end %>
</table>
<br>
<%= link_to "New article",new_admin_article_path,class:"button" %>
<br><br>

Ruby/app/views/admin/articles/new.html.erb
<!--<h1>New Article</h1>

<%= form_for @article do |f| %>
  Title name: <%= f.text_field :title %><br>
  <%=f.submit :Okay%>
<% end %>-->

<h1>Articles</h1>
	<%= form_for :article, url:admin_articles_path do |form| %>
	<% if @article.errors.any? %>
		<h4 style="color:red">
		    <%= pluralize(@article.errors.count, "error") %> prohibited this post from being saved:
		</h4>
	    <h3 style="color:red">
	        <% @article.errors.full_messages.each do |msg| %><br>
				<%= msg %>
			<% end %>
	    </h3>
		<% end %>

	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description,size:"70x15" %>
	</p>

	<p>
		<%= form.label :rating %><br>
		<%= form.select(:rating,options_for_select([[0],[1],[2],[3],[4],[5]])) %>
	</p>

	<p>
		<%= form.label :creator %><br>
		<%= form.collection_select :user_id,User.all,:id,:first_name %>
	</p>
	
	<p>
		<%= form.submit %> &nbsp; 
		<%= link_to "Back",admin_articles_path,class:"button" %>
	</p>
<% end %>

Ruby/app/views/admin/articles/show.html.erb
<h1>Articles</h1>
<article>
	<p>
		<strong>Title</strong><br>
		<%= @article.title %>
	</p>
	<p>
		<strong>Description</strong><br>
		<%= simple_format(@article.description) %>
	</p>
	<p>
		<strong>Rating</strong><br>
		<%= @article.rating %>
	</p>

	<p>
		<strong>Comments</strong><br>
		<div id="comments">
			<%= render :partial => "comments", :locals => {:comments => @article.comments} %>
			<!--partial:file_name @:from global  :comments : to local-->
		</div>
	</p> 
	<% unless(current_user.nil?)%> 
		<%= form_for :comment,:url=>comments_path, :remote => true do |form| %>
			<%= form.text_area :content,size:"50x5" %><br>
			<%= form.hidden_field :article_id,:value=>@article.id %>
			<%= submit_tag "Comment" %>
		<% end %>
	<% end %>
<%= link_to "Back",admin_articles_path,class:"button" %>
</article>